### ISSUE TITLE
IOError on opening some WOFF2 files

### ISSUE THREAD

**Issue by afoster** [friendsoftheweb/woff-rb#6]
Hi,

I'm seeing the following error when opening some WOFF2 files:

```
2.4.0-fostertype :001 > require 'woff'
 => true 

2.4.0-fostertype :002 > woff = WOFF::Builder.new('/path/to/Font.woff2')
 => #<WOFF::Builder:0x000000013cc9f8 @location="/path/to/Font.woff2"> 

2.4.0-fostertype :003 > woff.font_with_metadata
IOError: data truncated
	from /Users/andy/.rvm/gems/ruby-2.4.0-fostertype/gems/bindata-2.4.1/lib/bindata/io.rb:315:in `read'
	from /Users/andy/.rvm/gems/ruby-2.4.0-fostertype/gems/bindata-2.4.1/lib/bindata/io.rb:276:in `readbytes'
	from /Users/andy/.rvm/gems/ruby-2.4.0-fostertype/gems/bindata-2.4.1/lib/bindata/string.rb:118:in `read_and_return_value'
	from /Users/andy/.rvm/gems/ruby-2.4.0-fostertype/gems/bindata-2.4.1/lib/bindata/base_primitive.rb:129:in `do_read'
	from /Users/andy/.rvm/gems/ruby-2.4.0-fostertype/gems/bindata-2.4.1/lib/bindata/struct.rb:139:in `block in do_read'
	from /Users/andy/.rvm/gems/ruby-2.4.0-fostertype/gems/bindata-2.4.1/lib/bindata/struct.rb:139:in `each'
	from /Users/andy/.rvm/gems/ruby-2.4.0-fostertype/gems/bindata-2.4.1/lib/bindata/struct.rb:139:in `do_read'
	from /Users/andy/.rvm/gems/ruby-2.4.0-fostertype/gems/bindata-2.4.1/lib/bindata/base.rb:147:in `block in read'
	from /Users/andy/.rvm/gems/ruby-2.4.0-fostertype/gems/bindata-2.4.1/lib/bindata/base.rb:254:in `start_read'
	from /Users/andy/.rvm/gems/ruby-2.4.0-fostertype/gems/bindata-2.4.1/lib/bindata/base.rb:145:in `read'
	from /Users/andy/.rvm/gems/ruby-2.4.0-fostertype/gems/bindata-2.4.1/lib/bindata/base.rb:21:in `read'
	from /Users/andy/projects/github/woff-rb/lib/woff/file.rb:38:in `read'
	from /Users/andy/projects/github/woff-rb/lib/woff/builder.rb:82:in `data'
	from /Users/andy/projects/github/woff-rb/lib/woff/builder.rb:18:in `font_with_metadata'
	from (irb):6
	from /Users/andy/.rvm/rubies/ruby-2.4.0-fostertype/bin/irb:11:in `<main>'
```

Any idea what might cause this behaviour?

Also, I'm interested in helping out on woff2 writing support if that's of interest.

Thanks, Andy

**Comment by joshhepworth** [comment]
In the past, an error like that has usually meant I messed up the definition in WOFF::File::V2 – defined (here)[https://github.com/friendsoftheweb/woff-rb/blob/master/lib/woff/file.rb#L94-L150].

If you can upload (or email me) the particular WOFF2 file that you're having issues with, I can certainly take a look, but if you'd rather fix it and submit a PR I suspect that you'll want to look at the (WOFF File Format 2.0 spec)[https://www.w3.org/TR/WOFF2/] and the `UIntBase128` class. 

For some history there – WOFF 2 changed the format for the table directory to improve compression. This also significantly increased complexity and introduced a binary type that was not supported out of the box by the `bindata` gem. I essentially tried to just reimplement the C++ code I found defining the datatype, but as I don't _truly_ understand it, it's quite possible that I bungled the reimplementation. This would then give the wrong length to `bindata` for the table directory in the font, causing it to try to read past the end of the IO stream (or sometimes read short).

Anyway, let me know if you want to work on it and submit a PR, or if you'd be able to send me a failing WOFF2 file by some means.
